### PR TITLE
Close #220 - use Express' `req.is` to verify MIME type to be `application/json`

### LINKED ISSUE #220: Suggestion: mime-type verification method
### A description of the problem you're trying to solve.
Express has it's own method for checking mime-type (Request.is), but Nestia has implemented a duplicative method.

### An overview of the suggested solution.
1. using Express' Request.is
```ts
const request: express.Request = context.switchToHttp().getRequest();
if (!request.is("application/json")) {
    throw new BadRequestException(
        "Request body is not the application/json.",
    );
}
```

2. Or, Considering performance, using String.prototype.includes instead of current Split-Some method
```ts
const JSON_MIME_TYPE = "application/json";
const isApplicationJson = (text?: string) =>
    text === JSON_MIME_TYPE ||
    text !== undefined &&
    text.includes(JSON_MIME_TYPE);
```

[Benchmark between Split-Some and String.prototype.includes](https://perf.link/#eyJpZCI6InYwMGEyYTdkc3cyIiwidGl0bGUiOiJpc0FwcGxpY2F0aW9uSnNvbiIsImJlZm9yZSI6ImNvbnN0IGhlYWRlciA9IFwiYXBwbGljYXRpb24vanNvblwiO1xuY29uc3QgaGVhZGVyV2l0aFV0ZjggPSBcImFwcGxpY2F0aW9uL2pzb247IHV0Zi04XCI7XG5cbmNvbnN0IE1JTUVfVFlQRV9BUFBMSUNBVElPTl9KU09OID0gJ2FwcGxpY2F0aW9uL2pzb24nO1xuXG5jb25zdCBpc0FwcGxpY2F0aW9uSnNvbkJ5U3BsaXRTb21lID0gKHRleHQpID0%2BXG4gICAgdGV4dCAhPT0gdW5kZWZpbmVkICYmXG4gICAgdGV4dFxuICAgIC5zcGxpdChcIjtcIilcbiAgICAubWFwKChzdHIpID0%2BIHN0ci50cmltKCkpXG4gICAgLnNvbWUoKHN0cikgPT4gc3RyID09PSBNSU1FX1RZUEVfQVBQTElDQVRJT05fSlNPTik7XG5cbmNvbnN0IGlzQXBwbGljYXRpb25Kc29uQnlJbmNsdWRlcyA9ICh0ZXh0KSA9PlxuICAgIHRleHQgPT09IE1JTUVfVFlQRV9BUFBMSUNBVElPTl9KU09OIHx8XG4gICAgdGV4dCAhPT0gdW5kZWZpbmVkICYmXG4gICAgdGV4dC5pbmNsdWRlcyhNSU1FX1RZUEVfQVBQTElDQVRJT05fSlNPTik7XG5cbmNvbnN0IGlzQXBwbGljYXRpb25Kc29uQnlJZGVudGl0eU9wID0gKHRleHQpID0%2BXG4gICAgdGV4dCA9PT0gTUlNRV9UWVBFX0FQUExJQ0FUSU9OX0pTT047XG4gICIsInRlc3RzIjpbeyJuYW1lIjoiQ2hlY2sgaGVhZGVyIGJ5IElkZW50aXR5T3AiLCJjb2RlIjoiaXNBcHBsaWNhdGlvbkpzb25CeUlkZW50aXR5T3AoaGVhZGVyKTsiLCJydW5zIjpbMzIwNTAwMCwyOTE1MDAwLDIzMjEwMDAsMzg2NDAwMCwzODIwMDAsMjczNTAwMCw4NzkwMDAsMjMxMTAwMCw0Njk0MDAwLDQ0MDAwLDQ1OTQwMDAsMzA5MjAwMCw0MTI5MDAwLDEwMjkwMDAsNDQwMDAsMjUxNDAwMCw4MDUwMDAsMTgxMjAwMCw1MTQ3MDAwLDU2NTcwMDAsMjY0MTAwMCwxMTk2MDAwLDM3MzIwMDAsMjA0MTAwMCwyODA5MDAwLDE4MDIwMDAsMjczNjAwMCw0NDkxMDAwLDYwMDAwLDE4ODMwMDAsMTUxNzAwMCwxMDI0MDAwLDEwNDAwMCw0NTcwMDAsMTkzOTAwMCwyMTE0MDAwLDYyMDAwLDM4NDcwMDAsMzUxMzAwMCwzNzUxMDAwLDQ3MTMwMDAsNDQ2MDAwMCwzMzU5MDAwLDc3NTAwMCw0ODIxMDAwLDQ3MDkwMDAsNDk1NTAwMCwzNTMwMDAwLDMxNjYwMDAsMTUzNTAwMCw1MTA2MDAwLDIzNzcwMDAsMjA2NDAwMCw0MTY0MDAwLDM0NTYwMDAsMzQwOTAwMCwyMTY3MDAwLDMzNzEwMDAsNDQ1ODAwMCwzOTI3MDAwLDQ5MTkwMDAsMjA4NTAwMCw0ODEwMDAsNDMwNDAwMCw1MDc1MDAwLDI1NjEwMDAsOTY1MDAwLDI5NDYwMDAsNDUyMTAwMCw5NDEwMDAsMzIwMDAwLDQ2MzAwMCw0MjM3MDAwLDMzNjMwMDAsMzQxNTAwMCw1NjQ1MDAwLDI3NzEwMDAsNTIxMTAwMCw0NzE4MDAwLDQ2MzIwMDAsMzcyMDAwMCw1NTA3MDAwLDU2NTYwMDAsMzA1NzAwMCwzMTAwMCwyNDk2MDAwLDQ0MDcwMDAsMzg5NTAwMCwwLDIzMjIwMDAsNDgwMDAwMCwzMzgwMDAsMzE0MDAwLDQ0OTgwMDAsMTM0MjAwMCwxMzk1MDAwLDI5NDAwMDAsMzM2MjAwMCwyMDI5MDAwLDI4OTcwMDBdLCJvcHMiOjI4Mjk5MzB9LHsibmFtZSI6IkNoZWNrIGhlYWRlciBieSBTcGxpdFNvbWUiLCJjb2RlIjoiaXNBcHBsaWNhdGlvbkpzb25CeVNwbGl0U29tZShoZWFkZXIpOyIsInJ1bnMiOlsxMjc2MDAwLDkwMDAsMTA1NjAwMCw1MjYwMDAsMTI5MjAwMCw4NDEwMDAsMTAwMCw1NDgwMDAsMTI4MDAwMCw5MDAwLDEyODAwMDAsNDc1MDAwLDgxODAwMCwyNjcwMDAsNTYwMDAwLDEzNTMwMDAsMTgzMDAwLDEwMzgwMDAsMTM1MjAwMCw4OTkwMDAsMTM1MDAwLDgyMTAwMCwzMTMwMDAsNTUwMDAwLDU4MDAwMCwzODcwMDAsNzA2MDAwLDU4MTAwMCwzNzUwMDAsNzc0MDAwLDYwNTAwMCwzMjcwMDAsMTM1NjAwMCwxMjM5MDAwLDk0NDAwMCwxNDA3MDAwLDc0MDAwMCwxMDc3MDAwLDEwMTUwMDAsMTUxMDAwMCw0ODAwMDAsNDUyMDAwLDk4MjAwMCwxNTEyMDAwLDExODYwMDAsMTc3MDAwLDEyNjUwMDAsNTg1MDAwLDQ4NDAwMCw1MjEwMDAsMTIwNzAwMCw1MDAwMCwxMTYwMDAwLDExOTYwMDAsMTE2NTAwMCw1OTkwMDAsMTA0NTAwMCw0MDkwMDAsMTAwMCwxMzAyMDAwLDEyMzYwMDAsNTI3MDAwLDU2MDAwMCw1NDAwMDAsNDQ1MDAwLDc0MTAwMCw3MzAwMDAsNjk1MDAwLDEwMDAwLDIxNjAwMCw4OTEwMDAsMTAwMCw3OTcwMDAsMTA2MDAwMCwzMjQwMDAsOTY2MDAwLDEzODQwMDAsMjIyMDAwLDkxNzAwMCwxMTYzMDAwLDEyMzQwMDAsMTQ0OTAwMCwyNTgwMDAsNjIwMDAwLDEwMDAsNjM2MDAwLDkyMjAwMCwxNDQyMDAwLDI3NDAwMCwxMDY5MDAwLDEwMDAwLDk1ODAwMCw4OTIwMDAsMzEyMDAwLDEwMjAwMCw3MzkwMDAsNDUwMDAsNjU1MDAwLDg4NTAwMCwxMjc3MDAwXSwib3BzIjo3MzQ4ODB9LHsibmFtZSI6IkNoZWNrIGhlYWRlcldpdGhVdGY4IGJ5IFNwbGl0U29tZSIsImNvZGUiOiJpc0FwcGxpY2F0aW9uSnNvbkJ5U3BsaXRTb21lKGhlYWRlcldpdGhVdGY4KTsiLCJydW5zIjpbMjUwMDAsNjkyMDAwLDU1MDAwMCw4NzMwMDAsODgwMDAsNzM3MDAwLDUwMzAwMCwxMTcwMDAsMTA1NDAwMCw2NzcwMDAsNTcyMDAwLDUxMjAwMCw0NTEwMDAsNjIwMDAsNjAyMDAwLDEwMDUwMDAsMTA1MzAwMCwxMDAwMCw2NTYwMDAsMjc4MDAwLDEwMDEwMDAsMjYyMDAwLDEwNDYwMDAsOTkzMDAwLDEwMDAsMTExNjAwMCwxMDExMDAwLDQwMzAwMCwxNDUwMDAsNjY2MDAwLDEyMzQwMDAsMTE3MzAwMCw1MDAwLDQ1MTAwMCw2MDYwMDAsOTMzMDAwLDQ0NjAwMCwxMDAwLDEwODYwMDAsOTQ0MDAwLDExMzUwMDAsNDUyMDAwLDk1MjAwMCwxMzkwMDAsNTkzMDAwLDQwNzAwMCwxMDQxMDAwLDE4MzAwMCw2MjAwMCw5MTQwMDAsOTg4MDAwLDU0NDAwMCwxMDgwMDAwLDExMTQwMDAsMTI0MDAwMCw5OTIwMDAsMzE5MDAwLDEwNzkwMDAsMTE1NTAwMCw5ODkwMDAsNzUyMDAwLDQ3NzAwMCwxMzEwMDAsODgwMDAsMTE1NjAwMCwyMjcwMDAsODcwMDAwLDEwMDAsODA5MDAwLDc1MjAwMCw0NzkwMDAsODY0MDAwLDcwMDAwMCw2MDIwMDAsNjkyMDAwLDkwODAwMCw0MzUwMDAsNjQyMDAwLDExMTcwMDAsMTA3NjAwMCw5MDMwMDAsNjAyMDAwLDYwMjAwMCw5MDAwMCwxMjM0MDAwLDY4MTAwMCwzMzgwMDAsMTE5ODAwMCw3MDAwLDIwMDAsNjkyMDAwLDExNzAwMDAsNzY4MDAwLDQ1MTAwMCw2MDIwMDAsMjQxMDAwLDU0NDAwMCwxODAwMDAsNDgyMDAwLDcwMjAwMF0sIm9wcyI6NjM2ODUwfSx7Im5hbWUiOiJDaGVjayBoZWFkZXIgYnkgSW5jdWRlcyIsImNvZGUiOiJpc0FwcGxpY2F0aW9uSnNvbkJ5SW5jbHVkZXMoaGVhZGVyKTsiLCJydW5zIjpbMzAzOTAwMCwzMjE4MDAwLDEzMTIwMDAsMzUxMjAwMCw0MTAwMDAwLDMwMzEwMDAsNTE2MDAwLDExMzkwMDAsMjI3MzAwMCwxNzgyMDAwLDQxODAwMDAsMTQzNjAwMCwzMDYwMDAwLDU1NjAwMCwzNDkzMDAwLDgzNDAwMCw0MDQ0MDAwLDQxOTgwMDAsMzkwMjAwMCwxMzQxMDAwLDE3NjcwMDAsNDM4NjAwMCw1MzUxMDAwLDEwMjEwMDAsODAxMDAwLDM3MjYwMDAsMTk1MDAwLDI0MTAwMDAsMTE4MDAwLDE2MDAwLDQ4NTYwMDAsMjY5NTAwMCwyODEwMDAsNDA2MDAwLDE0MjkwMDAsNDI5MDAwLDMzODAwMCw1MDYxMDAwLDEwMjEwMDAsMTE3NDAwMCw0NDQwMDAwLDQ0MTIwMDAsODYxMDAwLDMwNDEwMDAsMTAxMjAwMCwxNzA0MDAwLDI0NzEwMDAsMTYyMDAwMCwxNTM0MDAwLDE0MjYwMDAsMjk3MDAwMCwxODAwMDAwLDMwNjkwMDAsNDQzNDAwMCwzNTgzMDAwLDUxMTcwMDAsNDk2NTAwMCw3MDcwMDAsNDA5MDAwMCwxODM4MDAwLDQ2OTAwMCwyMTUzMDAwLDIwMDAwLDkxNDAwMCw0NTMzMDAwLDEzNTgwMDAsNDk5MTAwMCw0NzQ0MDAwLDEyNjEwMDAsMjE5MDAwLDE0MzIwMDAsMTQ1OTAwMCwyMjYwMDAsMTMyMDAwMCw0ODEzMDAwLDQ2OTkwMDAsMzY5NDAwMCwzNjMxMDAwLDEzNzIwMDAsMTA1MjAwMCwzNzY1MDAwLDM4MzcwMDAsNDIzMjAwMCwyMjEyMDAwLDM3NzAwMDAsMjcyNjAwMCwxNDgwMDAsMTY5MjAwMCwzOTY0MDAwLDIwMjEwMDAsMjIwMDAwMCwxNjcyMDAwLDUzNDAwMCwxNTc4MDAwLDI0MzQwMDAsNDM2NTAwMCwxMDAwLDM4OTUwMDAsMTkzMzAwMCw0ODk5MDAwXSwib3BzIjoyMzk3NzkwfSx7Im5hbWUiOiJDaGVjayBoZWFkZXJXaXRoVXRmOCBieSBJbmN1ZGVzIiwiY29kZSI6ImlzQXBwbGljYXRpb25Kc29uQnlJbmNsdWRlcyhoZWFkZXJXaXRoVXRmOCk7IiwicnVucyI6WzEzNTgwMDAsMTEzMDAwLDQ1NTAwMCwxNTI1MDAwLDEwNjIwMDAsODg2MDAwLDMwNTAwMDAsNzAyMDAwLDE0MjgwMDAsMTM3NjAwMCwxNzQzMDAwLDMwNDEwMDAsMjcyNDAwMCwyMTg3MDAwLDMyNDQwMDAsMzg4MDAwLDE4MDMwMDAsMjQ3MzAwMCwyMjYwMDAsMjE5MTAwMCwyNjI0MDAwLDIxOTEwMDAsMjQxNDAwMCwxNTc4MDAwLDI1ODAwMDAsMTYxOTAwMCwzMDEzMDAwLDI5NDAwMCwxNDA2MDAwLDMwNzQwMDAsNTE4MDAwLDMyMjQwMDAsMjE1NTAwMCwxMTA2MDAwLDI5MjgwMDAsMTQxMDAwLDExOTAwMCwxMjcwMDAwLDMwNTIwMDAsMTExNTAwMCwyMzYwMDAsMTAwMCwxMTA1MDAwLDEzMTUwMDAsMjcxMjAwMCwxMzk5MDAwLDEwNjYwMDAsMzI1NzAwMCwxMTEzMDAwLDg1NjAwMCwxMjQ0MDAwLDI0MjAwMDAsMTAwMCwyMzQ5MDAwLDE5MzIwMDAsODcyMDAwLDMxOTgwMDAsMzk5MDAwLDk1ODAwMCwyNDExMDAwLDExMjgwMDAsMjE5MTAwMCwzMDgwMDAsMjYwMDAwLDU2MzAwMCwyOTgwMDAwLDM4NDAwMCwyOTg3MDAwLDMxMzAwMCwxMDcwMDAsMjE5MTAwMCwxMDMwMDAwLDIxNTAwMCw5MzAwMDAsMTQ3NTAwMCwxNzY1MDAwLDIxOTEwMDAsMzE0NzAwMCw4NTYwMDAsMjA0MDAwMCw0MTIwMDAsMjIzMzAwMCwyNjk5MDAwLDM0MzgwMDAsMjE5MTAwMCwyNTU0MDAwLDI4NTQwMDAsMzcxMjAwMCwxMjE3MDAwLDkwMDAwLDE0NzUwMDAsMTE3MDAwMCwzNDEwMDAsNDcwMDAwLDE0MjkwMDAsMjQyODAwMCwxMDAwLDI0ODUwMDAsMTM2NDAwMCwyNDk3MDAwXSwib3BzIjoxNTkzNjEwfV0sInVwZGF0ZWQiOiIyMDIzLTAxLTE4VDA0OjE4OjI0LjAyOFoifQ%3D%3D)

### PR DESCRIPTION
**Pull request by 39hn**
use Express' `req.is` to verify MIME type to be `application/json`

### CODE REVIEW

**Review by samchon — CHANGES_REQUESTED** [review]
Need to split `;` symbol and have to check strictly, because some wrong expression like `acr4json/application` can be passed by your code. What about using your first suggestion, `is()` method?

**Comment by 39hn** [comment]
You're right. have to check strictly.
I've benchmarked `req.is` and it's seems extreamly slow and changed my mind.
Current Split-Some method looks way more better to me atm.

how do you think?

**Comment by samchon** [comment]
The `is()` function seems clear and easy to read. I think do not need to consider performance for only one word parsing.

**Review by samchon — APPROVED** [review]
OK, accepted

**Pull request merged**
