### PR TITLE
add multer support for fastify

### PR DESCRIPTION
**Pull request by sergio-milu**
This PR implements the functionality discussed in this issue https://github.com/samchon/nestia/issues/819

I need some help with the testing though, cause I cannot make test run in my computer @samchon 

Thanks :)

### CODE REVIEW

**Review by samchon — COMMENTED** [review]
https://github.com/samchon/nestia/issues/819#issuecomment-2211135908

**Comment by sergio-milu** [comment]
> [#819 (comment)](https://github.com/samchon/nestia/issues/819#issuecomment-2211135908)

any news here?

**Comment by sergio-milu** [comment]
@samchon any news about this PR? has been 4 months, you asked us for a PR and we opened one, if you will discard this, just told us and we will make a fork cause we need this feature in order to fully migrate to nestia

**Comment by samchon** [comment]
Preparing major update to dependent libraries `@samchon/openapi` and `typia`.

After these libraries' major updates, `nestia` will also take the major update too, and this PR would be accept at that time.

The next major update may come in a month.

**Review by samchon — COMMENTED** [review]
Even though it fails, merge it anyway for detailed debugging.

**Comment by samchon** [comment]
Well, not working on CJS

https://github.com/samchon/nestia/actions/runs/12042762353/job/33576977029

**Pull request merged**
