### PR TITLE
Enhance #446 add signal to IConnection.IOptions

### PR DESCRIPTION
**Pull request by mmamedel**

### CODE REVIEW

**Review by samchon — COMMENTED** [review]
Is it okay that assigning real `AbortSignal` to this interface type?

As you know, `AbortSignal` is a class type of the DOM.

```typescript
/**
 * A signal object that allows you to communicate with a DOM request (such as a Fetch) and abort it if required via an AbortController object.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal)
 */
interface AbortSignal extends EventTarget {
    /**
     * Returns true if this AbortSignal's AbortController has signaled to abort, and false otherwise.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal/aborted)
     */
    readonly aborted: boolean;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal/abort_event) */
    onabort: ((this: AbortSignal, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal/reason) */
    readonly reason: any;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal/throwIfAborted) */
    throwIfAborted(): void;
    addEventListener<K extends keyof AbortSignalEventMap>(type: K, listener: (this: AbortSignal, ev: AbortSignalEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof AbortSignalEventMap>(type: K, listener: (this: AbortSignal, ev: AbortSignalEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var AbortSignal: {
    prototype: AbortSignal;
    new(): AbortSignal;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal/abort) */
    abort(reason?: any): AbortSignal;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal/timeout) */
    timeout(milliseconds: number): AbortSignal;
};
```

**Comment by mmamedel** [comment]
> Is it okay that assigning real `AbortSignal` to this interface type?
> 
> As you know, `AbortSignal` is a class type of the DOM.
> 
> ```ts
> /**
>  * A signal object that allows you to communicate with a DOM request (such as a Fetch) and abort it if required via an AbortController object.
>  *
>  * [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal)
>  */
> interface AbortSignal extends EventTarget {
>     /**
>      * Returns true if this AbortSignal's AbortController has signaled to abort, and false otherwise.
>      *
>      * [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal/aborted)
>      */
>     readonly aborted: boolean;
>     /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal/abort_event) */
>     onabort: ((this: AbortSignal, ev: Event) => any) | null;
>     /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal/reason) */
>     readonly reason: any;
>     /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal/throwIfAborted) */
>     throwIfAborted(): void;
>     addEventListener<K extends keyof AbortSignalEventMap>(type: K, listener: (this: AbortSignal, ev: AbortSignalEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
>     addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
>     removeEventListener<K extends keyof AbortSignalEventMap>(type: K, listener: (this: AbortSignal, ev: AbortSignalEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
>     removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
> }
> 
> declare var AbortSignal: {
>     prototype: AbortSignal;
>     new(): AbortSignal;
>     /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal/abort) */
>     abort(reason?: any): AbortSignal;
>     /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AbortSignal/timeout) */
>     timeout(milliseconds: number): AbortSignal;
> };
> ```

Sure, I made the change.

**Review by samchon — APPROVED** [review]
Will publish after testing.

**Comment by samchon** [comment]
Published to v1.6. Thanks @mmamedel and let's enjoy the new version.

**Pull request merged**
